### ISSUE TITLE
Floating texts appear in all worlds

### ISSUE THREAD

**Issue by UnEnanoMas** [OguzhanUmutlu/DynamicFT#5]
![image](https://user-images.githubusercontent.com/63286108/115714196-24df9400-a377-11eb-8679-771a53b5fd58.png)
![image](https://user-images.githubusercontent.com/63286108/115714320-4771ad00-a377-11eb-87f3-f9ff12286e71.png)

**Comment by OguzhanUmutlu** [comment]
Thanks for reporting bug! I am gonna fix it.

**Comment by OguzhanUmutlu** [comment]
@UnEnanoMas i fixed the issue you can download it here: https://poggit.pmmp.io/r/124033/DynamicFT_dev-43.phar

It will be approved in 2-3 days in poggit.
