### ISSUE TITLE
You cannot use the {line}

### ISSUE THREAD

**Issue by UnEnanoMas** [OguzhanUmutlu/DynamicFT#6]
![image](https://user-images.githubusercontent.com/63286108/116906264-50e4fa00-ac40-11eb-90de-d2bf2419fc26.png)

**Comment by OguzhanUmutlu** [comment]
So it's not the latest version.

**Comment by UnEnanoMas** [comment]
@OguzhanUmutlu 

DynamicFT_dev-44.phar

????

**Comment by OguzhanUmutlu** [comment]
You can check the code there is {line} maybe you used another plugin

**Comment by UnEnanoMas** [comment]
I am not using another plugin, please is logic
